config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users

  root to: 'pages#homees'

  get "/ulule" => redirect("https://fr.ulule.com/sylki")
  resources :beers
  resources :guests
  resources :tastings

  resources :contacts
  resources :participations, only: [:new, :index, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/models/brasserie.rb
class Brasserie < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true

  after_create :subscribe_to_newsletter

  private

  def subscribe_to_newsletter
    SubscribeToNewsletterService.new(self).call
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :tastings, through: :participations, inverse_of: :guest
  has_many :participations

  validates :firstname, presence: true, uniqueness: { scope: :lastname }
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))\z/, message: "merci de rentrer un email correct"}

  accepts_nested_attributes_for :participations, allow_destroy: true
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :guest, inverse_of: :participations
  belongs_to :tasting

end

app/models/tasting.rb
class Tasting < ApplicationRecord
  has_many :guests, through: :participations, dependent: :destroy
  has_many :participations, dependent: :destroy

  validates :date, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.all
  end

  def create
    @beer = beer.new(beer_params)
    if @beer.save
      redirect_to beers_path
    else
      render :new
    end
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def new
    @beer = Beer.new
  end

  def update
    @beer = Beer.find(params[:id])
    if @beer.update(beer_params)
      redirect_to beer_path(@beer)
    else
      render :new
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :type, :recipe, :grade)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @contacts = Contact.all
  end

  def create
    @contact = Contact.new(contact_params)
    if !Contact.where(email: @contact.email).exists?
      @contact.save
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    if @contact.destroy
      redirect_to tastings_path
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @guests = Guest.all
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.save
    @participation = Participation.new
    @participation.guest_id = params["guest"]["participations_attributes"]["0"]["guest_id"]
    @participation.tasting_id = params["guest"]["participations_attributes"]["0"]["tasting_id"]
    if @participation.save && @guest.save
      redirect_to root_path
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def update
    @guest = Guest.find(params[:id])
    if @guest.update(guest_params)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def guest_params
    params.require(:guest).permit(:firstname, :lastname, :email, :participation_attributes => [:id, :guest_id, :tasting_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @participation = Participation.new
    @contact = Contact.new
    @guest = Guest.new

    @brasserie = Brasserie.where.not(latitude: nil, longitude: nil)
    @markers = @brasserie.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude#,
        # infoWindow: { content: render_to_string(partial: "/locations/map_box", locals: { location: location }) }
      }
    end
  end

  def homees
    @contact = Contact.new
  end

end

app/controllers/tastings_controller.rb
class TastingsController < ApplicationController

  def index
    @tastings = Tasting.all
    @tasting = Tasting.new
  end

  def create
    @tasting = Tasting.new(tasting_params)
    if @tasting.save
      redirect_to tastings_path
    else
      render :new
    end
  end

  def destroy
    @tasting = Tasting.find(params[:id])
    @participations = Participation.where(tasting_id: @tasting.id)
    if @participations.first != nil
      @participations.destroy_all
    end
    @tasting.delete
    if @tasting.delete
      redirect_to tastings_path
    end
  end

  def show
    @tasting = Tasting.find(params[:id])
  end

  def edit
    @tasting = Tasting.find(params[:id])
  end

  def new
    @tasting = Tasting.new
  end

  def update
    @tasting = Tasting.find(params[:id])
    if @tasting.update(tasting_params)
      redirect_to tastings_path
    else
      render :new
    end
  end

  private

  def tasting_params
    params.require(:tasting).permit(:date, :capacity, :open, :ipa, :ambree, :surprise, :blonde)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/brasserie_helper.rb
module BrasserieHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/tastings_helper.rb
module TastingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_new.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.hidden_field :email, as: :string %>
  <%= f.button :submit, style: "display: none;", value: "Envoyer aux brasseurs" %>
<% end %>

app/views/guests/_new.html.erb
<%= form_for @guest do |f| %>
  <p>
    Prénom: <%= f.text_field :firstname %>
  </p>
  <p>
    Nom: <%= f.text_field :lastname %>
  </p>
  <p>
    e-mail: <%= f.text_field :email %>
  </p>
  <%= f.fields_for :participations, @participation do |participation_form| %>
    <% if Guest.last != nil %>
      <%= participation_form.hidden_field :guest_id, :value => (Guest.last.id + 1) %>
      <% else  %>
      <%= participation_form.hidden_field :guest_id, :value => 1 %>
    <% end %>
    <%= participation_form.hidden_field :tasting_id, :value => (Tasting.where(open: true).first.id) %>
  <% end %>
  <p>
    <%= f.submit "s'enregistrer", id: "inscription" %>
  </p>
<% end %>

app/views/tastings/_form.html.erb
<%= simple_form_for(@tasting) do |f| %>
  <%= f.input :date, as: :string %>
  <%= f.input :capacity, label: "Capacité", as: :integer %>
  <%= f.input :ipa %>
  <%= f.input :ambree %>
  <%= f.input :surprise %>
  <%= f.input :blonde %>
  <%= f.button :submit, value: "Créer une dégustation" %>
<% end %>

app/views/tastings/_new.html.erb
<h1> Créer un nouveau tasting </h1>

<%= render 'tastings/form' %>

app/views/tastings/edit.html.erb
<div class="edit-tastings">

  <%= simple_form_for(@tasting) do |f| %>
    <h3>Modifier la dégustation</h3>
    <%= f.input :date, as: :string, placeholder: @tasting.date  %>
    <%= f.input :capacity, as: :integer, placeholder: @tasting.capacity %>
    <%= f.input :open, as: :boolean, checked_value: true, unchecked_value: false %>
    <h3>Liste des bières proposées :</h3>
    <div class="bierlist">
      <%= f.input :ipa, as: :boolean, checked_value: true, unchecked_value: false %>
      <%= f.input :ambree, as: :boolean, checked_value: true, unchecked_value: false %>
      <%= f.input :surprise, as: :boolean, checked_value: true, unchecked_value: false %>
      <%= f.input :blonde, as: :boolean, checked_value: true, unchecked_value: false %>
    </div>
    <%= f.button :submit %>
  <% end %>

 <%= link_to "Retour à l'espace brasseur", tastings_path %>

</div>

app/views/tastings/index.html.erb
<% if current_user.admin? %>
<div class="index-tastings">

  <h1>Liste des dégustations prévues</h1>
  <div class="tableau-tastings">
    <div class="row">
      <div class="col-xs-3">
        <p>Date</p>
      </div>
      <div class="col-xs-3">
        <p>Nombre de places totales</p>
      </div>
      <div class="col-xs-3">
        <p>Inscriptions ouvertes?</p>
      </div>
      <div class="col-xs-3">
        <p>Actions</p>
      </div>
    </div>
    <% @tastings.each do |tasting| %>
      <div class="row">
        <div class="col-xs-3">
          <%= tasting.date %>
          (
          <% if tasting.ambree? %>
            ambrée
          <% end %>
          <% if tasting.surprise? %>
            , surprise
          <% end %>
          <% if tasting.blonde? %>
            , blonde
          <% end %>
          <% if tasting.ipa? %>
            , IPA
          <% end %>
          )
        </div>
        <div class="col-xs-3">
          <%= tasting.capacity %>
        </div>
        <div class="col-xs-3">
          <% if tasting.open? %>
            <p>Oui</p>
          <% else %>
            <p>Non</p>
          <% end %>
        </div>
        <div class="col-xs-3">
          <%= link_to edit_tasting_path(tasting.id) do %>
            <p>Modifier</p>
          <% end %>
          <%= link_to tasting_path(tasting.id), method: :delete, data: { confirm: "Supprimer cette dégustation?" } do %>
            <p>Supprimer</p>
          <% end %>
        </div>

      </div>
    <% end %>
  </div>

  <%= render 'tastings/new' %>

  <h1>Participants à la prochaine dégustation</h1>
  <% targetTasting = Tasting.where(open: true).first %>
  <% if targetTasting != nil %>
    <h4>
        <%= targetTasting.date %>
        -  <% places = (targetTasting.capacity - Participation.where(tasting_id: targetTasting.id).count) %>
        <%= places %> places restantes
    </h4>
    <% if targetTasting.participations.first != nil %>
      <div class="tableau-guests">
        <div class="row">
          <% targetTasting.participations.each do |p| %>
            <div class="col-xs-6">
              <%= p.guest.firstname %> <%= p.guest.lastname %>
            </div>
            <div class="col-xs-6">
              <%= p.guest.email %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="export-to-clipboard">
        <h4>
          <%= link_to "Afficher la liste des mails" %>
        </h4>
      </div>
    <% else %>
      <p> Aucun inscrits pour le moment</p>
    <% end %>
  <% else %>
    Aucune dégustation ouverte pour le moment
  <% end %>

  <h1>Messages reçus</h1>
  <div class="tableau-messages">
    <div class="row">
      <% if Contact.first != nil %>
        <% allMessages = Contact.all %>
        <% allMessages.each do |m| %>
          <div class="col-xs-4">
            <% if m.name? %>
              <p>Nom: </p>
              <%= m.name %>
            <% end %>
          </div>
          <div class="col-xs-4">
            <p>E-mail: </p>
            <%= m.email %>
          </div>
          <div class="col-xs-4">
          <%= link_to contact_path(m.id), method: :delete do %>
            <p>Supprimer ce message</p>
          <% end %>
          </div>
          <div class="col-xs-12">
            <%= m.message %>
          </div>
        <% end %>
      <% else %>
        <div class="no-msg">
          Aucun message pour le moment
        </div>
      <% end %>
    </div>
  </div>

  <h1>Brasseurs enregistrés</h1>
  <div class="tableau-users">
    <div class="row">
      <div class="col-xs-6">
        <p>e-mail</p>
      </div>
      <div class="col-xs-6">
        <p>Brasseur certifié?</p>
      </div>
    </div>
    <% User.all.each do |user| %>
      <div class="row">
        <div class="col-xs-6">
          <%= user.email %>
        </div>
        <div class="col-xs-6">
          <% if user.admin? %>
           <p> oui </p>
          <% else %>
           <p> non </p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to "Retour à l'accueil", root_path %>
</div>
<% else %>
<div class="index-tastings" id="fail-brasseur">
  <h1>Désolé, votre statut de brasseur n'a pas encore été validé par l'administrateur</h1>
  <p>N'hésitez pas à envoyer un mail à Nicolas pour qu'il vous débloque l'accès !</p>
  <p>
    <%= link_to "Retour à l'accueil", root_path %>
  </p>
</div>
<% end %>